site_name: Portal Link Documentation

nav:
  - Home: index.md
  - 通用語言: ubiquitous_language.md
  - 身份驗證機制: auth.md
  - Modules:
    - User 領域:
      - Domain:
        - Error: modules/user/domain/error.md
        - User 實體: modules/user/domain/user_entity.md
      - Usecase:
        - Sign Up 註冊: modules/user/usecase/sign_up_uc.md
        - Sign In 登入: modules/user/usecase/sign_in_uc.md
    - Portal Page 領域:
      - Domain:
        - Error: modules/portal_page/domain/error.md
        - Enum: modules/portal_page/domain/enum.md
        - Portal Page 實體: modules/portal_page/domain/portal_page_entity.md
        - Link 實體: modules/portal_page/domain/link_entity.md
      - Usecase:
        - Create Portal Page 建立頁面: modules/portal_page/usecase/create_portal_page_uc.md

docs_dir: docs

theme:
  name: material
